first-join:
  enabled: true
  line_count: 5
  message:
    line1: "#808080&m===================="
    line2: ""
    line3: "#00FF00&lWelcome #FFFF00%player_name% #808080to the server! #808080[&f#%unique_join_count%#808080]"
    line4: ""
    line5: "#808080&m===================="

welcome-command:
  enabled: true
  cooldown: 60
  reward-amount: 100.0
  welcome-message: "#00FF00Welcome to the server, #FFFF00%target_name%#00FF00! Welcomed by #FFFF00%player_name%"
  success-message: "#00FF00You welcomed a new player and received %reward_amount% coins!"
  no-new-players: "#FF0000That player has already been welcomed!"
  cooldown-message: "#FF0000Please wait %seconds% seconds before using this command again!"