name: PlayerWelcomer
version: 1.0.1
main: carnage.playerWelcomer.PlayerWelcomer
api-version: '1.21'
depend: [Vault]
commands:
  welcome:
    description: Welcome a new player and receive a reward
    usage: /<command> <player>
  welcomereload:
    description: Reloads the plugin's configuration
    usage: /<command>
permissions:
  playerwelcomer.admin:
    description: Allows using the /welcomereload command
    default: op